### ISSUE TITLE
bug: ddu-ui-filer

### ISSUE THREAD

**Issue by mikanIchinose** [mikanIchinose/ddu-source-markdown#5]
### environment

nvim: v0.9.0-dev-198+g75ec1b720
mac: 12.6

### minimal setting

```vim
" minimal setting
set runtimepath^=path/to/denops.vim
set runtimepath^=path/to/ddu.vim
set runtimepath^=path/to/ddu-kind-file
set runtimepath^=path/to/ddu-ui-filer
set runtimepath^=path/to/ddu-source-markdown

augroup Ddu
  autocmd!
  autocmd FileType ddu-filer nnoremap <buffer> o <Cmd>call ddu#ui#filer#do_action('expandItem', {'mode': 'toggle'})<CR>
augroup END

call ddu#custom#patch_global({
      \ 'sources': [{'name': 'markdown'}],
      \ 'ui': 'filer',
      \ 'uiParams': {'filer': {'sort': 'size'}}
      \ })
```

sample.md

```markdown
# header1

hoge

## header2

fuga

### header3

hoge

# headerA

hgoe

## subHeaderA-1

hgoe

## subHeaderA-2

hgoe

### subSubHeaderA

hgoe

# headerB

hgoe

## subHeaderB

hgoe
```

### instruction

1. open sample.md
2. call ddu#start()
    - The order of headers is not expected
      expected
      ```
      # header1
      ## header2
      ### header3
      # headerA
      ## subHeaderA-1
      ## subHeaderA-2
      ### subSubHeaderA
      # headerB
      ## subHeaderB
      ```
      actual
      ```
      # header1
      ## header2
      # headerA
      ## subHeaderA-2
      # headerB
      ### header3
      ## subHeaderA-1
      ### subSubHeaderA
      ## subHeaderB
      ```
3. move cursor at headerB
4. press <kbd>o</kbd>
6. press <kbd>o</kbd>
7. move cursor at subHeaderB
8. press <kbd>o</kbd>
9. move cursor at headerB
10. press <kbd>o</kbd>
    expected: expandItem
    actual: cursor down

https://user-images.githubusercontent.com/29175998/198941879-37d53379-0e86-4ee0-ada7-31d688407ce8.mov

**Comment by Shougo** [comment]
You must disable sort like this.

```vim
call ddu#custom#patch_local('filer', {
      \   'ui': 'filer',
      \   'sources': [
      \     {
      \       'name': 'markdown',
      \       'params': {},
      \     },
      \   ],
      \   'sourceOptions': {
      \     '_': {
      \       'columns': ['icon_filename'],
      \     },
      \   },
      \   'uiParams': {
      \     'filer': {
      \       'winWidth': 40,
      \       'sort': 'none',
      \       'sortDirectoriesFirst': v:false,
      \       'split': 'vertical',
      \       'splitDirection': 'topleft',
      \     }
      \   },
      \ })
```

**Comment by mikanIchinose** [comment]
Thank you.
The order of headers problem is fixed.

**Comment by Shougo** [comment]
`expandItem` problem is fixed?

**Comment by Shougo** [comment]
Fixed.  Please update `ddu-ui-filer`.

**Comment by mikanIchinose** [comment]
It is still happened..

### minimal setting

```vim
set runtimepath^=path/to/denops.vim
set runtimepath^=path/to/ddu.vim
set runtimepath^=path/to/ddu-kind-file
set runtimepath^=path/to/ddu-ui-filer
set runtimepath^=path/to/ddu-source-markdown

augroup Ddu
  autocmd!
  autocmd FileType ddu-filer nnoremap <buffer> o <Cmd>call ddu#ui#filer#do_action('expandItem', {'mode': 'toggle'})<CR>
augroup END

call ddu#custom#patch_global({
      \ 'sources': [{'name': 'markdown'}],
      \ 'ui': 'filer',
      \ 'uiParams': {
      \   'filer': {
      \     'sort': 'none',
      \     'sortDirectoriesFirst': v:false,
      \   },
      \ },
      \ })
```

### sample.md

same

### instruction

1. open sample.md
2. `:call ddu#start()`
3. move cursor to header1
4. press <kbd>o</kbd>
5. press <kbd>o</kbd> again
6. move cursor to header2
7. press <kbd>o</kbd>
8. move cursor to header3
9. press <kbd>o</kbd>
10. move cursor to header1
11. press <kbd>o</kbd>
    expected: close tree
    actual: move cursor to header3


https://user-images.githubusercontent.com/29175998/199002909-013b9100-df59-41f1-8357-ada8335adc51.mov

**Comment by Shougo** [comment]
Fixed.  Please update.

**Comment by mikanIchinose** [comment]
It fixed 🎉 🎉 . Wonderful!!
Thank you.
